Cph/Models/ProjectListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Cph.Data;

namespace Cph.Models
{
    public class ProjectListModel
    {
        public IList<Project> Projects { get; set; }
    }
}

Cph/Models/TeamListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Cph.Data;

namespace Cph.Models
{
    public class TeamListModel
    {
        public IList<Member> Members { get; set; }
    }
}

Cph/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cph.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Cph/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cph.Aids;
using Cph.Data;
using Cph.Hubs;
using Cph.Models;
using Microsoft.AspNet.SignalR;

namespace Cph.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly CphDb db = new CphDb();

        public ActionResult Index()
        {
            var model = new ProjectListModel
                {
                    Projects = db.Projects.OrderByDescending(p => p.Started).ToList()
                };
            return View(model);
        }

        public ActionResult Details(string name)
        {
            var project = GetProject(name);

            if (project == null)
            {
                return HttpNotFound();
            }

            return View(project);
        }

        public ActionResult Edit(string name)
        {
            var project = GetProject(name);

            if (project == null)
            {
                return HttpNotFound();
            }

            return View(project);
        }

        public ActionResult EditForm(string name)
        {
            var project = GetProject(name);

            if (project == null)
            {
                return HttpNotFound();
            }

            return PartialView(project);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();

                // update other clients
                var @lockHub = GlobalHost.ConnectionManager.GetHubContext<LockHub>();
                @lockHub.Clients.All.update(project.GetEntityId());

                return RedirectToAction("Details", new {name = project.Name});
            }

            return View(project);
        }

        private Project GetProject(string name)
        {
            return db.Projects.FirstOrDefault(p => p.Name.ToLower() == name.ToLower());
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Cph/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cph.Data;

namespace Cph.Controllers
{
    public class TeamController : Controller
    {
        private readonly CphDb db = new CphDb();

        public ActionResult Index()
        {
            var team = db.Teams.First(t => t.Name == "CPH Alpha Team");

            return View(team);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Cph/Controllers/TechController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cph.Controllers
{
    public class TechController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ReleaseNotes()
        {
            return View();
        }
    }
}

Cph/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<h1 class="page-header">Welcome to CPH team!</h1>
<p>Meet us on our @Html.ActionLink("team page", "Index", "Team") or see our @Html.ActionLink("projects", "Index", "Projects")</p>

Cph/Views/Projects/Details.cshtml
@using Newtonsoft.Json
@model Cph.Data.Project

@{
    ViewBag.Title = Model.Name;
}
<hgroup class="page-header page-header-project">
    <h1 class="header-inline">@Model.Name</h1>
    @Html.ActionLink("Edit", "Edit", new {name = Model.Name}, new {@class = "header-action-link"})
    <h4>@Model.Description</h4>
</hgroup>
<div class="row">
    <div id="project-info" class="col-md-12"></div>
</div>
<hr />
<h3>Dev Team</h3>
<div class="row">
    @foreach (var member in Model.DevTeam)
    {
        @Html.DisplayFor(m => member)
    }
</div>
<hr />
<h3>Service Team</h3>
<div class="row">
    @foreach (var member in Model.ServiceTeam)
    {
        @Html.DisplayFor(m => member)
    }
</div>
@section scripts{
    <script>
        var md = new Markdown.Converter();
        var html = md.makeHtml(@Html.Raw(JsonConvert.SerializeObject(Model.Info)));
        $('#project-info').html(html);
    </script>
}

Cph/Views/Projects/Edit.cshtml
@model Cph.Data.Project
@{
    ViewBag.Title = "Edit";
}
<h1 class="page-header">Edit project</h1>
<div id="project-edit" class="row">
    @{Html.RenderPartial("EditForm");}
</div>
    
@section scripts {
    <script src="~/signalr/hubs"></script>
    <script>
        var locker = new cph.Locker('@Model.GetEntityId()', {
            $editBox: $('#project-edit'),
            ajaxUrl: '@Url.Action("EditForm", new {name = Model.Name})'
        });
    </script>
}

Cph/Views/Projects/EditForm.cshtml
@model Cph.Data.Project
<div class="col-md-6 col-sm-6 col-xs-12">
    @using (Html.BeginForm("Edit", "Projects", new {name = Model.Name}, FormMethod.Post, new {@class = "form-horizontal"}))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            @*<legend>@Model.Name</legend>*@
            
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new {@class = "col-md-2 control-label"})
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.Name, null, new {@class = "help-block"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Description, new {@class = "col-md-2 control-label"})
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Description, new {@class = "form-control", style = "resize: none;", rows = "2"})
                    @Html.ValidationMessageFor(m => m.Description, null, new {@class = "help-block"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Started, new {@class = "col-md-2 control-label"})
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Started, "{0:dd/MM/yyyy}", new {@class = "form-control datepicker"})
                    @Html.ValidationMessageFor(m => m.Started, null, new {@class = "help-block"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Ended, new {@class = "col-md-2 control-label"})
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Ended, "{0:dd/MM/yyyy}", new {@class = "form-control datepicker"})
                    @Html.ValidationMessageFor(m => m.Ended, null, new {@class = "help-block"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.TopImage, new {@class = "col-md-2 control-label"})
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.TopImage, new {type = "url", @class = "form-control"})
                    @Html.ValidationMessageFor(m => m.TopImage, null, new {@class = "help-block"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Info, new {@class = "col-md-2 control-label"})
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Info, new {@class = "form-control markdown", style = "resize: none;", rows = "10"})
                    @Html.ValidationMessageFor(m => m.Info, null, new {@class = "help-block"})
                </div>
            </div>
        
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        </fieldset>
    }
</div>
<div class="col-md-6 col-sm-6 col-xs-12 markdown-preview">
</div>

Cph/Views/Projects/Index.cshtml
@model  Cph.Models.ProjectListModel

@{
    ViewBag.Title = "Projects";
}
<h1 class="page-header">Projects</h1>
<ul class="list-unstyled">
    @foreach (var project in Model.Projects)
    {
        <li>
            <h2>@project.Name</h2>
            <h4>@project.Description</h4>
            @Html.ActionLink("Details", "Details", new {name = project.Name})
        </li>
    }
</ul>

Cph/Views/Shared/DisplayTemplates/Member.cshtml
@model Cph.Data.Member

<div class="col-md-4 col-sm-6 col-xs-12 team-member">
    <img class="img-responsive" src="@Model.Photo?w=340&h=193&mode=crop" width="340" />
    <h2>@Model.FullName</h2>
    <h4 class="mate-position">@Model.Position</h4>
    <ul class="list-inline">
        <li><a href="mailto:@Model.Email"><i class="icon-envelope icon-2x"></i></a></li>
        @foreach (var link in Model.SocialLinks)
        {
            <li>
                <a href="@link.Url" target="_blank">
                    <i class="@link.Service.ToSocialIconClass() icon-2x" title="@link.Service.Name"></i>
                </a>
            </li>
        }
    </ul>
</div>

Cph/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title - CPH</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        @Styles.Render("~/bundles/css")
    </head>
    <body>
        <header class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">CPH</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @Html.MenuItem("Home", "Index", "Home")
                        @Html.MenuItem("Team", "Index", "Team")
                        @Html.MenuItem("Projects", "Index", "Projects")
                        @Html.MenuItem("Tech", "Index", "Tech")
                    </ul>
                </div>
            </div>
        </header>
        <main id="content" class="container">
            @RenderBody()
        </main>
        <footer class="container" role="contentinfo">
            @{
                var version = System.Diagnostics.FileVersionInfo.GetVersionInfo(typeof (Cph.MvcApplication).Assembly.Location).FileVersion;
            }
            <hr>@Html.ActionLink("v" + version, "ReleaseNotes", "Tech") © 2013 Creuna CPH | Clone on <a href="https://github.com/whyleee/Cph">GitHub</a>
        </footer>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/js")
        @RenderSection("scripts", required: false)
    </body>
</html>

Cph/Views/Team/Index.cshtml
@model Cph.Data.Team

@{
    ViewBag.Title = "Team";
}
<h1 class="page-header">@Model.Name</h1>
<div class="row">
    @foreach(var member in Model.Members)
    {
        @Html.DisplayFor(m => member)
    }
</div>

Cph/Views/Tech/Index.cshtml
@{
    ViewBag.Title = "Tech";
}

<h1>Oops, nothing here yet..</h1>
<img src="http://d31887jkx2z9wr.cloudfront.net/dancers/banana.gif"/>

Cph/Views/Tech/ReleaseNotes.cshtml
@{
    ViewBag.Title = "Release notes";
}

<h1 class="page-header">Release notes</h1>
<ul class="release-notes list-unstyled">
    <li>
        <h2>v0.1.1.1</h2>
        <ul>
            <li>Small markdown editor fixes</li>
        </ul>
    </li>
    <li>
        <h2>v0.1.1</h2>
        <ul>
            <li>@Html.ActionLink("Collaborative edit", "Edit", "Projects", new {name = "Hay"}, null) using locks and web-sockets</li>
            <li>@Html.ActionLink("Release notes page", "ReleaseNotes")</li>
        </ul>
    </li>
    <li>
        <h2>v0.1</h2>
        <ul>
            <li>@Html.ActionLink("Team page", "Index", "Team") will alpha team members and social links.</li>
            <li>@Html.ActionLink("Projects page", "Index", "Projects") with list of our projects.</li>
            <li>@Html.ActionLink("Project details page", "Details", "Projects", new {name = "QualiWare"}, null) with info about the project and its devs.</li>
            <li>@Html.ActionLink("Project edit page", "Edit", "Projects", new {name = "Nobia"}, null), where you can edit basic project info.</li>
            <li>@Html.ActionLink("Live markdown editor", "Edit", "Projects", new {name = "Nobia"}, null) for project info.</li>
        </ul>
    </li>
</ul>